# Generated by Django 4.2.5 on 2023-09-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorinfomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('dimage', models.FileField(upload_to='mgmt_app/static')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('select', models.CharField(choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('MS', 'MS'), ('BAMS', 'BAMS'), ('BHMS', 'BHMS')], max_length=50)),
                ('specialization', models.CharField(max_length=250)),
                ('about', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
