# Generated by Django 4.2.5 on 2023-09-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_app', '0004_questionsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='answermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diname', models.CharField(max_length=100)),
                ('explanation', models.CharField(max_length=1000)),
                ('remedy', models.CharField(max_length=500)),
            ],
        ),
    ]
