# Generated by Django 4.2.5 on 2023-10-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_app', '0006_commentsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=100)),
                ('himage', models.FileField(upload_to='mgmt_app/static')),
                ('about', models.CharField(max_length=600)),
            ],
        ),
    ]
